SRCS += \
	$(NXDK_DIR)/lib/xboxrt/libc_extensions/stat.c \
	$(NXDK_DIR)/lib/xboxrt/libc_extensions/strings.c \
	$(NXDK_DIR)/lib/xboxrt/libc_extensions/wchar.c \
	$(NXDK_DIR)/lib/xboxrt/libc_extensions/stdlib_ext_.c \
	$(NXDK_DIR)/lib/xboxrt/libc_extensions/string_ext_.c \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_alldiv.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_allmul.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_allrem.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_allshl.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_allshr.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_aulldiv.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_aullrem.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_aullshl.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_aullshr.s \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/_fltused.c \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/check_stack.c \
	$(NXDK_DIR)/lib/xboxrt/c_runtime/chkstk.s \
	$(NXDK_DIR)/lib/xboxrt/vcruntime/vcruntime_exception.cpp
