// SPDX-License-Identifier: MIT

// SPDX-FileCopyrightText: 2019 Stefan Schmidt

#ifndef __WINAPIFAMILY_H__
#define __WINAPIFAMILY_H__

#define WINAPI_FAMILY_PC_APP      2
#define WINAPI_FAMILY_PHONE_APP   3
#define WINAPI_FAMILY_SYSTEM      4
#define WINAPI_FAMILY_SERVER      5
#define WINAPI_FAMILY_DESKTOP_APP 100

#ifndef WINAPI_FAMILY
#define WINAPI_FAMILY WINAPI_FAMILY_DESKTOP_APP
#endif

#ifndef WINAPI_PARTITION_DESKTOP
#define WINAPI_PARTITION_DESKTOP (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)
#endif

#define WINAPI_FAMILY_PARTITION(partition) (partition)

#endif
