SRCS += \
	$(wildcard $(NXDK_DIR)/lib/winapi/*.c) \
	$(wildcard $(NXDK_DIR)/lib/pbkit/*.c)

include $(NXDK_DIR)/lib/Makefile-pdclib
include $(NXDK_DIR)/lib/hal/Makefile
include $(NXDK_DIR)/lib/nxdk/Makefile
include $(NXDK_DIR)/lib/usb/Makefile
include $(NXDK_DIR)/lib/xboxrt/Makefile
include $(NXDK_DIR)/lib/zlib/Makefile
