struct vIn {
	float4 color    : DIFFUSE;
	float4 position : POSITION;
};

struct vOut {
	float4 col : COLOR;
	float4 pos : POSITION;
};

vOut main(
	vIn              I,
	uniform float4x4 m_viewport
	)
{
	vOut   result;
	float4 position;

	position = mul(float4(I.position.xyz, 1.0f), m_viewport);
	position.xyz = position.xyz / position.w;

	result.col = I.color;
	result.pos = position;
	return result;
}
